# SPDX-License-Identifier: MIT
#
# File:    docs/man/Makefile
# Author:  Jiří Kučera, <sanczes AT gmail.com>
# Date:    2020-03-21 14:38:42 +0100
# Project: A CLI Shell Library (clishe)
# Brief:   Build manual pages.
#

.PHONY: docs install clean

docs:
	$(MAKE) -C man7 $(MAKECMDGOALS)

install:
	$(MAKE) -C man7 $(MAKECMDGOALS)

clean:
	$(MAKE) -C man7 $(MAKECMDGOALS)
